# 用于服务发现
[rpc]
    prefix = "etcd://chat_room/"
    connRpcPrefix = "room_conn"

# 用于服务注册
[srv]
    srvName = "room_job" # 服务名
    listenAddr = "127.0.0.1:6002" # 服务监听地址
    ttl = 5 # 心跳时间（秒）

# etcd服务
[etcd]
    addrs = ["127.0.0.1:2379"]
    dialTimeOut = 5

#nsq服务
[nsq]
    addr = "127.0.0.1:4150"
    topic = "chat_room"